baseurl: '/'
permalink: pretty
title: 'Software Tech Principal Pathways'

logo:
  mobile: "images/logo/logo.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "64px"
  desktop_width: "120px"

collections:
  articles:
    output: false
  articlesCategories:
    output: true
  services:
    output: false
  team:
    output: false
  workshops:
    output: false

defaults:
  - scope:
      path: ""
      type: "services"
    values: 
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "workshops"
    values:
      layout: "service"

sass:
  indentWidth: 4
  style: compressed # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
